language: rust
before_script:
 - cargo install cargo-web
 - rustup component add rustfmt
script:
  - make build
  - cargo fmt -- --check
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: code