language: rust
before_script:
 - cargo install cargo-web
 - rustup component add rustfmt
script:
  - make build
  - cargo fmt -- --check
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  fqdn: zhouyuxiang.com
  on:
    branch: master
# after_success: |
#   [ $TRAVIS_BRANCH = code ] &&
#   [ $TRAVIS_PULL_REQUEST = false ] &&
#   sudo pip install --upgrade pip &&
#   sudo pip install pipe &&
#   sudo pipe install ghp-import &&
#   ghp-import -c https://zhouyuxiang0.github.io -n docs -b master &&
#   git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
